# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Context < Formula
  desc "Local-first runtime for AI-assisted engineering"
  homepage "https://github.com/PRNVBAJAJ/context-os"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PRNVBAJAJ/context-os/releases/download/v0.1.4/context_0.1.4_darwin_amd64.tar.gz"
      sha256 "1c527436b8e845945acbe8163d786bc32582aa3b83fd4196bce103f46316593f"

      define_method(:install) do
        bin.install "context"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PRNVBAJAJ/context-os/releases/download/v0.1.4/context_0.1.4_darwin_arm64.tar.gz"
      sha256 "cc10ff88d87e1b68153e3e372e16e2c2759186f70356228cb3d222a3de877ba7"

      define_method(:install) do
        bin.install "context"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PRNVBAJAJ/context-os/releases/download/v0.1.4/context_0.1.4_linux_amd64.tar.gz"
      sha256 "0724828a73643dd993e35fb0659749d6734599449a90b607ad2e8bb2f3fa1aa1"
      define_method(:install) do
        bin.install "context"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PRNVBAJAJ/context-os/releases/download/v0.1.4/context_0.1.4_linux_arm64.tar.gz"
      sha256 "ae46bdafb59a1ba2a01c3557085df41dd195611f09696428ee18c58ea36fb173"
      define_method(:install) do
        bin.install "context"
      end
    end
  end

  test do
    system "#{bin}/context", "--version"
  end
end
