# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Context < Formula
  desc "Local-first runtime for AI-assisted engineering"
  homepage "https://github.com/PRNVBAJAJ/context-os"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PRNVBAJAJ/context-os/releases/download/v0.3.0/context_0.3.0_darwin_amd64.tar.gz"
      sha256 "16be307404b6501c090d9e1821d480ed3e8e00b29a2bc05ec6207a80e59b5474"

      define_method(:install) do
        bin.install "context"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PRNVBAJAJ/context-os/releases/download/v0.3.0/context_0.3.0_darwin_arm64.tar.gz"
      sha256 "ab2e52d38f8223a7edda54c8ed98c45500ff3f0d948d9bc4c42babfde6c42ce5"

      define_method(:install) do
        bin.install "context"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PRNVBAJAJ/context-os/releases/download/v0.3.0/context_0.3.0_linux_amd64.tar.gz"
      sha256 "cc73c5663488d5acb3ec341eb0d7407a6616f65654a8a7bd11cc88bdc601feaf"
      define_method(:install) do
        bin.install "context"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PRNVBAJAJ/context-os/releases/download/v0.3.0/context_0.3.0_linux_arm64.tar.gz"
      sha256 "9da3dad37f7f309ee2daeb49a0811396434177f668e5abd7ff2df569765d40e6"
      define_method(:install) do
        bin.install "context"
      end
    end
  end

  test do
    system "#{bin}/context", "--version"
  end
end
